from __future__ import annotations

FOLLOWUP_DELAY_MIN_HOURS = 4
FOLLOWUP_DELAY_MAX_HOURS = 6
ACTIVE_DISCUSSION_WINDOW_HOURS = 2
ACTIVE_DISCUSSION_MESSAGE_THRESHOLD = 20
ACTIVE_DISCUSSION_UNIQUE_USERS_THRESHOLD = 5
MAX_BOT_MESSAGES_PER_THREAD = 3
MAX_BOT_MESSAGES_IN_A_ROW = 2
ANTI_REPEAT_DAYS_PER_CHAT = 90
