from __future__ import annotations

DEFAULT_COMMUNITY_CHAT_KEYS: tuple[str, ...] = (
    "left4portugal",
    "chatlisboa",
    "chatporto",
    "chatleiria",
    "chatalgarve",
    "chatalcochete",
    "chatfigueira",
)

DEFAULT_CHAT_DEFINITIONS: tuple[dict[str, object], ...] = (
    {
        "chat_id": -1001620974633,
        "chat_key": "left4portugal",
        "chat_type": "global",
        "region": None,
        "has_topics": False,
        "default_topic_id": None,
        "is_enabled": False,
        "daily_post_time": "11:00",
        "max_posts_per_day": 1,
        "cooldown_hours": 24,
    },
    {
        "chat_id": -1001656765898,
        "chat_key": "chatlisboa",
        "chat_type": "local",
        "region": "lisboa",
        "has_topics": False,
        "default_topic_id": None,
        "is_enabled": False,
        "daily_post_time": "11:00",
        "max_posts_per_day": 1,
        "cooldown_hours": 24,
    },
    {
        "chat_id": -1001719116315,
        "chat_key": "chatporto",
        "chat_type": "local",
        "region": "porto",
        "has_topics": False,
        "default_topic_id": None,
        "is_enabled": False,
        "daily_post_time": "11:00",
        "max_posts_per_day": 1,
        "cooldown_hours": 24,
    },
    {
        "chat_id": -1001227461571,
        "chat_key": "chatleiria",
        "chat_type": "local",
        "region": "leiria",
        "has_topics": False,
        "default_topic_id": None,
        "is_enabled": False,
        "daily_post_time": "11:00",
        "max_posts_per_day": 1,
        "cooldown_hours": 24,
    },
    {
        "chat_id": -1001690275466,
        "chat_key": "chatalgarve",
        "chat_type": "local",
        "region": "algarve",
        "has_topics": False,
        "default_topic_id": None,
        "is_enabled": False,
        "daily_post_time": "11:00",
        "max_posts_per_day": 1,
        "cooldown_hours": 24,
    },
    {
        "chat_id": -1001975356498,
        "chat_key": "chatalcochete",
        "chat_type": "local",
        "region": "alcochete",
        "has_topics": False,
        "default_topic_id": None,
        "is_enabled": False,
        "daily_post_time": "11:00",
        "max_posts_per_day": 1,
        "cooldown_hours": 24,
    },
    {
        "chat_id": -1002102744104,
        "chat_key": "chatfigueira",
        "chat_type": "local",
        "region": "figueira",
        "has_topics": False,
        "default_topic_id": None,
        "is_enabled": False,
        "daily_post_time": "11:00",
        "max_posts_per_day": 1,
        "cooldown_hours": 24,
    },
)
