#!/usr/bin/env bash
# ==============================================================================
# DO NOT RUN -- PREPARE ONLY
# ==============================================================================
# Generated by verb_tranche1_prepare.py on 2026-04-18T14:01:40Z.
# Activates verb tranche 1 items in data/lingua_staging.db.
#
# ACTIVATION IS NOT AUTHORIZED until all of the following are true:
#   1. verb_monitoring_runner.py verdict = PREPARE_NEXT_TRANCHE
#      (minimum 30 sessions, >= 3 real users)
#   2. At least one of T1-T4 has fired
#   3. No active item with pct_correct < 20%
#   4. Rule 1 anti-collision re-check against expanded active bank complete
#
# Usage (dry-run, default):
#   bash diagnostics_exports/verb_tranche1/current/verb_tranche1_apply_DONOTRUN.sh
# Usage (apply -- only when authorized):
#   bash diagnostics_exports/verb_tranche1/current/verb_tranche1_apply_DONOTRUN.sh --apply
# ==============================================================================

set -euo pipefail

DB="data/lingua_staging.db"
APPLY=0

for arg in "$@"; do
  case "$arg" in
    --apply) APPLY=1 ;;
    *) echo "Unknown argument: $arg"; exit 1 ;;
  esac
done

echo "DO NOT RUN / PREPARE ONLY script for verb tranche 1"
echo "DB: $DB"

# 0 selected items:
SELECTED_IDS=""

echo ""
echo "Items that would be activated:"

echo ""
echo "Pre-flight checks..."

# Check 1: all items exist with is_active=0 and pos=verb
COUNT=$(sqlite3 "$DB" "SELECT COUNT(*) FROM vocab_items WHERE id IN () AND pos='verb' AND is_active=0;")
if [ "$COUNT" -ne 0 ]; then
  echo "FAIL: Expected 0 inactive verb items, found $COUNT"
  exit 1
fi
  echo "  PASS: 0 items found in DB with pos=verb AND is_active=0"

# Check 2: no active lemma duplicates
DUP_COUNT=$(sqlite3 "$DB" "SELECT COUNT(*) FROM vocab_items vi1 JOIN vocab_items vi2 ON vi1.lemma=vi2.lemma WHERE vi1.id IN () AND vi2.is_active=1 AND vi1.id != vi2.id;")
if [ "$DUP_COUNT" -ne 0 ]; then
  echo "FAIL: $DUP_COUNT duplicate lemmas found in active bank"
  exit 1
fi
  echo "  PASS: No duplicate lemmas in active bank"

# Check 3: Rule 1a — new correct_answers not in any active distractor set
R1A=$(sqlite3 "$DB" "SELECT COUNT(*) FROM vocab_items vi_new JOIN vocab_choices vc ON vc.choice_text=vi_new.correct_answer JOIN vocab_items vi_act ON vi_act.id=vc.item_id WHERE vi_new.id IN () AND vc.is_correct=0 AND vi_act.is_active=1;")
if [ "$R1A" -ne 0 ]; then
  echo "FAIL: Rule 1a -- $R1A new correct_answers appear in active distractors"
  exit 1
fi
  echo "  PASS: Rule 1a"

# Check 4: Rule 1b — active correct_answers not in new item distractors
R1B=$(sqlite3 "$DB" "SELECT COUNT(*) FROM vocab_choices vc_new JOIN vocab_items vi_new ON vi_new.id=vc_new.item_id JOIN vocab_items vi_act ON vi_act.correct_answer=vc_new.choice_text WHERE vi_new.id IN () AND vc_new.is_correct=0 AND vi_act.is_active=1;")
if [ "$R1B" -ne 0 ]; then
  echo "FAIL: Rule 1b -- $R1B active correct_answers in new distractors"
  exit 1
fi
  echo "  PASS: Rule 1b"

# Check 5: noun/10K wave1 untouched (guard rail)
N10K=$(sqlite3 "$DB" "SELECT COUNT(*) FROM vocab_items WHERE pos='noun' AND bin_name='10K' AND is_active=1;")
if [ "$N10K" -ne 13 ]; then
  echo "FAIL: noun/10K wave1 guard: expected 13 active items, found $N10K"
  exit 1
fi
  echo "  PASS: noun/10K wave1 guard (13 items intact)"

echo ""
if [ "$APPLY" -eq 0 ]; then
  echo "DRY RUN -- no changes made."
  echo "Re-run with --apply to activate 0 verb tranche 1 items."
  exit 0
fi

# ---- ACTIVATION (only reached with --apply) ----
echo "Activating 0 verb tranche 1 items..."
sqlite3 "$DB" "UPDATE vocab_items SET is_active=1, updated_at=datetime('now') WHERE id IN ();"

ACTIVATED=$(sqlite3 "$DB" "SELECT COUNT(*) FROM vocab_items WHERE id IN () AND is_active=1;")
echo "Activated: $ACTIVATED items"
if [ "$ACTIVATED" -ne 0 ]; then
  echo "FAIL: Expected 0 activated, found $ACTIVATED"
  exit 1
fi

echo ""
echo "Post-activation active verb count by bin:"
for BIN in 1K 2K 5K 10K 20K; do
  CNT=$(sqlite3 "$DB" "SELECT COUNT(*) FROM vocab_items WHERE pos='verb' AND bin_name='$BIN' AND is_active=1;")
  echo "  $BIN: $CNT"
done
echo "DONE -- verb tranche 1 activated."
