#!/usr/bin/env bash
# ==============================================================================
# DO NOT RUN -- PREPARE ONLY
# ==============================================================================
# Generated by noun10k_tranche2_prepare.py on 2026-04-18T10:53:55Z.
# Activates noun/10K tranche 2 items in data/lingua_staging.db.
#
# ACTIVATION IS NOT AUTHORIZED until all of the following are true:
#   1. noun10k_monitoring_runner.py verdict = PREPARE_NEXT_TRANCHE
#      (minimum 30 sessions, >= 3 real users)
#   2. At least one of T1-T4 has fired
#   3. No active item with pct_correct < 20%
#   4. Rule 1 anti-collision re-check against expanded active bank complete
#
# Usage (dry-run):
#   bash diagnostics_exports/current/noun10k_tranche2_apply_DONOTRUN.sh
# Usage (apply -- only when authorized):
#   bash diagnostics_exports/current/noun10k_tranche2_apply_DONOTRUN.sh --apply
# ==============================================================================

set -euo pipefail

DB="data/lingua_staging.db"
APPLY=0

for arg in "$@"; do
  case "$arg" in
    --apply) APPLY=1 ;;
    *) echo "Unknown argument: $arg"; exit 1 ;;
  esac
done

echo "DO NOT RUN / PREPARE ONLY script for noun/10K tranche 2"
echo "DB: $DB"

# 10 selected items:
SELECTED_IDS="10734, 10738, 10740, 10743, 10745, 10746, 10764, 10765, 10770, 10771"

echo ""
echo "Items that would be activated:"
echo "  10734  bigode"
echo "  10738  penhasco"
echo "  10740  orvalho"
echo "  10743  ferida"
echo "  10745  agulha"
echo "  10746  peneira"
echo "  10764  esquilo"
echo "  10765  javali"
echo "  10770  emboscada"
echo "  10771  sindicato"

echo ""
echo "Pre-flight checks..."

# Check: all items exist with is_active=0
COUNT=$(sqlite3 "$DB" "SELECT COUNT(*) FROM vocab_items WHERE id IN (10734, 10738, 10740, 10743, 10745, 10746, 10764, 10765, 10770, 10771) AND pos='noun' AND bin_name='10K' AND is_active=0;")
if [ "$COUNT" -ne 10 ]; then
  echo "FAIL: Expected 10 inactive noun/10K items, found $COUNT"
  exit 1
fi
  echo "  PASS: 10 items found in DB with is_active=0"

# Check: no active lemma duplicates
DUP_COUNT=$(sqlite3 "$DB" "SELECT COUNT(*) FROM vocab_items vi1 JOIN vocab_items vi2 ON vi1.lemma=vi2.lemma WHERE vi1.id IN (10734, 10738, 10740, 10743, 10745, 10746, 10764, 10765, 10770, 10771) AND vi2.is_active=1 AND vi1.id != vi2.id;")
if [ "$DUP_COUNT" -ne 0 ]; then
  echo "FAIL: $DUP_COUNT duplicate lemmas found in active bank"
  exit 1
fi
  echo "  PASS: No duplicate lemmas in active bank"

# Rule 1a: new correct_answers not in active bank distractors
R1A=$(sqlite3 "$DB" "SELECT COUNT(*) FROM vocab_items vi_new JOIN vocab_choices vc ON vc.choice_text=vi_new.correct_answer JOIN vocab_items vi_act ON vi_act.id=vc.item_id WHERE vi_new.id IN (10734, 10738, 10740, 10743, 10745, 10746, 10764, 10765, 10770, 10771) AND vc.is_correct=0 AND vi_act.is_active=1;")
if [ "$R1A" -ne 0 ]; then
  echo "FAIL: Rule 1a -- $R1A new correct_answers in active distractors"
  exit 1
fi
  echo "  PASS: Rule 1a"

# Rule 1b: active correct_answers not in new item distractors
R1B=$(sqlite3 "$DB" "SELECT COUNT(*) FROM vocab_choices vc_new JOIN vocab_items vi_new ON vi_new.id=vc_new.item_id JOIN vocab_items vi_act ON vi_act.correct_answer=vc_new.choice_text WHERE vi_new.id IN (10734, 10738, 10740, 10743, 10745, 10746, 10764, 10765, 10770, 10771) AND vc_new.is_correct=0 AND vi_act.is_active=1;")
if [ "$R1B" -ne 0 ]; then
  echo "FAIL: Rule 1b -- $R1B active correct_answers in new distractors"
  exit 1
fi
  echo "  PASS: Rule 1b"

echo ""
if [ "$APPLY" -eq 0 ]; then
  echo "DRY RUN -- no changes made."
  echo "Re-run with --apply to activate 10 items."
  exit 0
fi

echo "Activating 10 noun/10K tranche 2 items..."
sqlite3 "$DB" "UPDATE vocab_items SET is_active=1, updated_at=datetime('now') WHERE id IN (10734, 10738, 10740, 10743, 10745, 10746, 10764, 10765, 10770, 10771);"

ACTIVATED=$(sqlite3 "$DB" "SELECT COUNT(*) FROM vocab_items WHERE id IN (10734, 10738, 10740, 10743, 10745, 10746, 10764, 10765, 10770, 10771) AND is_active=1;")
echo "Activated: $ACTIVATED items"
if [ "$ACTIVATED" -ne 10 ]; then
  echo "FAIL: Expected 10 activated, found $ACTIVATED"
  exit 1
fi

echo ""
echo "Post-activation active noun/10K count:"
sqlite3 "$DB" "SELECT COUNT(*) FROM vocab_items WHERE pos='noun' AND bin_name='10K' AND is_active=1;"
echo "DONE -- tranche 2 activated."
